on: push
name: Test

jobs:
    runTest:
        name: Run npm test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run npm tests
              uses: actions/setup-node@v1
              
            - run: npm install
            - run: npm test
              env:
                CI: true
            